# -*- coding: utf-8 -*-
"""decision_tree

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ExFr_mxtUUJZixP1-jmWaBvA2TcyMWl5
"""

import pandas as pd
from google.colab import files
  
uploaded = files.upload()

df = pd.read_csv("w.csv")
df.head()

inputs = df.drop('salary_more_then_100k',axis='columns')
target = df['salary_more_then_100k']

from sklearn.preprocessing import LabelEncoder

le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_company.fit_transform(inputs['job'])
inputs['degree_n'] = le_company.fit_transform(inputs['degree'])

inputs.head()

inputs_n = inputs.drop(['company', 'job', 'degree'], axis='columns')
inputs_n

from sklearn import tree

model = tree.DecisionTreeClassifier()

model.fit(inputs_n, target)

model.score(inputs_n,target)

#google | sales exec | with masters
model.predict([[2,2,1]])

#facebook | sales exec | with masters
model.predict([[1,1,1]])

